# Generated by Django 2.1.2 on 2018-10-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
